### ISSUE TITLE
✨ [Feature] interface에 LocBlock을 추가 + LocBlock에서 error_code vector getter

### ISSUE THREAD

**Issue by Hawardshin** [42masterplan/webserv#13]
## ✨ 이슈 체크리스트

- [x] 이슈 제목: [Feature] '기능 내용 상세'
- [X] Assignees, Label을 붙여주세요.

## 📄 기능 개요
- interface에 LocBlock을 추가
- LocBlock에서 error_code vector getter추가

## 📝 기능 상세 내용
- parsing을 해주면서 location block이 특정되기 때문에 ServBlock을 찾아서 LocBlock 클래스 변수를 udata에 인터페이스에 추가해야한다고 느꼈습니다.
- 추가적으로 error_code vector를 얻는게 LocBlock에서 빠져서 그 부분 추가하고자 합니다.

## ✅ TODO

- [x] LocBlock에 vector getter
- [x] udata interface에 LocBlock 멤버변수 추가
