### ISSUE TITLE
✨ [Feature] 쿠키 추가관련 요청

### ISSUE THREAD

**Issue by Hawardshin** [42masterplan/webserv#28]
## ✨ 이슈 체크리스트

- [x] 이슈 제목: [Feature] '기능 내용 상세'
- [x] Assignees, Label을 붙여주세요.

## 📄 기능 개요

- 보너스에 쿠키와 세션 파트가 있습니다.

## 📝 기능 상세 내용
- 쿠키 세션 구현을 위해서 필요한 것은 다음과 같습니다.
- 그에 따라서 request측에서는 Cookie헤더를 받아야하고
- response측에서는 쿠키가 있다면 아무것도 하지 않고 쿠키가 없다면 새로운 세션을 만들어서 Set-Cookie: 헤더에 세션 ID를 담아서 보내주면 될 것 같습니다.
- 어딘가에 Session ID에 대한 값을 가지고 있어야 해서 그것을 저장할 위치도 지정해야합니다.
- 저희는 세션 쿠키만을 구현하면 될 것 같아서 굳이 유효기간을 설정하지는 않겠습니다.(이래도 되나..?)

## ✅ TODO

- [x] request Cookie 헤더 파싱
- [x] 세션을 저장할 저장소 코드에 추가
- [x] 세션 저장소를 확인해서 response 에 Set-Cookie 헤더 추가
